-- ============================================================================
-- DISABLE RLS FOR DEVELOPMENT
-- ============================================================================
-- WARNING: This is for DEVELOPMENT ONLY!
-- In production, you should create proper RLS policies instead.
-- ============================================================================

-- Disable RLS on all tables
ALTER TABLE developer DISABLE ROW LEVEL SECURITY;
ALTER TABLE admin DISABLE ROW LEVEL SECURITY;
ALTER TABLE enterprise DISABLE ROW LEVEL SECURITY;
ALTER TABLE "user" DISABLE ROW LEVEL SECURITY;
ALTER TABLE room DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_rooms DISABLE ROW LEVEL SECURITY;
ALTER TABLE task_template DISABLE ROW LEVEL SECURITY;
ALTER TABLE assigned_task DISABLE ROW LEVEL SECURITY;
ALTER TABLE cleaning_session DISABLE ROW LEVEL SECURITY;
ALTER TABLE cleaning_log DISABLE ROW LEVEL SECURITY;
ALTER TABLE export DISABLE ROW LEVEL SECURITY;
ALTER TABLE child DISABLE ROW LEVEL SECURITY;
ALTER TABLE supplier DISABLE ROW LEVEL SECURITY;
ALTER TABLE product DISABLE ROW LEVEL SECURITY;
ALTER TABLE batch DISABLE ROW LEVEL SECURITY;
ALTER TABLE meal DISABLE ROW LEVEL SECURITY;
ALTER TABLE temperature DISABLE ROW LEVEL SECURITY;
ALTER TABLE meal_children DISABLE ROW LEVEL SECURITY;
ALTER TABLE equipment DISABLE ROW LEVEL SECURITY;
ALTER TABLE cleaning_haccp DISABLE ROW LEVEL SECURITY;
ALTER TABLE non_compliance DISABLE ROW LEVEL SECURITY;
ALTER TABLE document DISABLE ROW LEVEL SECURITY;
ALTER TABLE conversation DISABLE ROW LEVEL SECURITY;
ALTER TABLE message DISABLE ROW LEVEL SECURITY;
ALTER TABLE notification DISABLE ROW LEVEL SECURITY;
